"""
Function 3: SPICE Netlist Review & Correction Agent.

This agent acts as a "Visual Netlist Auditor". It takes the SPICE code generated
by Function 2, compares it against the source images (both segmented and full),
detects hallucinations (like label blindness), and applies corrections in-place.
"""

import os
from pathlib import Path
from typing import List, Optional

from pydantic import SecretStr
from google.cloud import storage

from openhands.sdk import (
    LLM,
    Agent,
    Conversation,
    Event,
    ImageContent,
    LLMConvertibleEvent,
    Message,
    TextContent,
    get_logger,
)
from openhands.sdk.tool.spec import Tool
from openhands.tools.file_editor import FileEditorTool
from openhands.tools.task_tracker import TaskTrackerTool
from openhands.tools.terminal import TerminalTool

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# GCS Helper (Reused from Function 2)
# ---------------------------------------------------------------------------

def upload_image_to_gcs(
    local_path: Path,
    bucket_name: str,
    prefix: str = "schematic_subcircuits/",
    make_public: bool = False,
) -> str:
    """
    Uploads image to GCS and returns URI.
    """
    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blob_name = f"{prefix}{local_path.name}"
    blob = bucket.blob(blob_name)
    
    if not blob.exists(): # Optimization: Don't re-upload if exists
        blob.upload_from_filename(str(local_path))
    
    if make_public:
        blob.make_public()
        return blob.public_url
    return f"gs://{bucket_name}/{blob_name}"

# ---------------------------------------------------------------------------
# System Prompt: The "Auditor" Persona
# ---------------------------------------------------------------------------

def build_review_system_prompt() -> str:
    return """
You are a Senior Analog IC Design Reviewer and SPICE Auditor.
Your goal is to verify and correct SPICE code generated by a junior agent.
You value ACCURACY above all else. You are looking for hallucinations,
incorrect node names, and connectivity errors.

YOUR WORKFLOW
-------------
1. **Visual Scan**: Look at the provided images (Segmented View is primary). 
   Identify every visible text label attached to a wire (e.g., "BAT", "AVDD").
2. **Netlist Verification**: Compare these visible labels to the `.NET` or node 
   names in the provided SPICE code.
3. **Topology Check**: Pick random components and trace their connections visually. 
   Does the SPICE match the visual topology?

CRITICAL ERROR TYPES TO FIX
---------------------------
1. **Label Blindness (Hallucination)**: 
   - Error: The SPICE uses a generic name like `PWR_R5_OUT` or `NET01`, but the 
     image clearly shows a text label like `BAT` on that wire.
   - Fix: You MUST rename the node in the SPICE file to match the image label (`BAT`).
   
2. **Pin Misalignment**:
   - Error: The SPICE connects a component to Pin 1, but the image shows it 
     connected to Pin 2.
   - Fix: Rewire the component in SPICE to match the image.

3. **Floating Nodes**:
   - Error: A node is defined but never connected to anything, or a component 
     pin is left floating when it clearly connects to a wire in the image.
   - Fix: Connect it correctly.

CORRECTION PROTOCOL
-------------------
- Use the `FileEditorTool` to overwrite the SPICE file with the corrected version.
- **DO NOT** rewrite the whole file if it is already correct.
- **DO NOT** change standard SPICE syntax or component values unless they are 
  visibly wrong (e.g., reading 10k as 1k).
- **IC STUBS**: Ensure IC stubs (subcircuits) have the correct number of pins 
  as seen in the symbol.

OUTPUT
------
- If you find errors, fix them in the file using FileEditorTool.
- Provide a brief summary of your fixes in the chat (e.g., "Renamed PWR_R5_OUT to BAT").
- If the file is perfect, state "PASSED" and do not edit the file.
""".strip()

# ---------------------------------------------------------------------------
# Main Pipeline: Function 3 (Review)
# ---------------------------------------------------------------------------

def run_spice_review_pipeline(
    segmented_images_subdir: str = "../function_1/schematic_subcircuits",
    spice_input_subdir: str = "spice_subcircuits", # Output of Function 2
    full_schematic_path: Optional[str] = None,     # Path to original full image
    gcs_bucket_name: str = "vhl",
    gcs_prefix: str = "schematic_review/",
):
    """
    Function 3: Iterates over generated SPICE files and their corresponding images.
    Uses an Agent to audit and fix the SPICE code.
    """
    # ----------------------------------------------------------------------
    # Resolve paths
    # ----------------------------------------------------------------------
    script_dir = Path(__file__).resolve().parent
    images_dir = script_dir / segmented_images_subdir
    spice_dir = script_dir / spice_input_subdir

    if not spice_dir.exists():
        raise FileNotFoundError(f"SPICE directory not found: {spice_dir}. Run Function 2 first.")

    # Get list of SPICE files
    spice_files = sorted(list(spice_dir.glob("*.cir")))
    logger.info(f"Found {len(spice_files)} SPICE files to review")

    # ----------------------------------------------------------------------
    # Upload Full Schematic (Once)
    # ----------------------------------------------------------------------
    full_schematic_url = None
    if full_schematic_path:
        full_path = Path(full_schematic_path).resolve()
        if full_path.exists():
            logger.info(f"Uploading full schematic reference: {full_path.name}")
            full_schematic_url = upload_image_to_gcs(
                full_path, gcs_bucket_name, prefix=gcs_prefix
            )
        else:
            logger.warning(f"Full schematic path provided but not found: {full_schematic_path}")

    # ----------------------------------------------------------------------
    # Configure LLM (Reviewer needs high reasoning, e.g., Gemini 1.5 Pro)
    # ----------------------------------------------------------------------
    api_key = os.getenv("LLM_API_KEY")
    # Ideally use a stronger model for review than generation
    model = os.getenv("LLM_REVIEW_MODEL", "google/gemini-1.5-pro-002") 
    
    llm = LLM(
        usage_id="review-llm",
        model=model,
        api_key=SecretStr(api_key),
    )
    
    cwd = os.getcwd()

    agent = Agent(
        llm=llm,
        tools=[
            Tool(name=TerminalTool.name),
            Tool(name=FileEditorTool.name), # Critical for fixing the file
        ],
    )

    system_prompt = build_review_system_prompt()

    # ----------------------------------------------------------------------
    # Process each SPICE file
    # ----------------------------------------------------------------------
    for spice_file in spice_files:
        # Find corresponding image
        image_stem = spice_file.stem # e.g., subckt_003
        
        # Look for matching image with supported extensions
        img_path = None
        for ext in [".png", ".jpg", ".jpeg"]:
            candidate = images_dir / f"{image_stem}{ext}"
            if candidate.exists():
                img_path = candidate
                break
        
        if not img_path:
            logger.warning(f"Skipping review for {spice_file.name}: No matching image found.")
            continue

        logger.info(f"Reviewing: {spice_file.name} against {img_path.name}")

        # 1. Upload Segmented Image
        seg_img_url = upload_image_to_gcs(
            img_path, gcs_bucket_name, prefix=gcs_prefix
        )

        # 2. Read existing SPICE content to pass in prompt
        # (This saves the agent a step of reading it manually)
        current_spice_content = spice_file.read_text(encoding='utf-8')

        # 3. Construct the Task Prompt
        user_instruction = f"""
STARTING REVIEW TASK
--------------------
**Target File**: {spice_file.name}
**Path**: {spice_file.resolve()}

**Current SPICE Content**:
```spice
{current_spice_content}
````

**Instructions**:

1.  Analyze the **Segmented Image** (attached) closely.

2.  (Optional) Check the **Full Schematic** (attached) if you need global context for wire destinations.

3.  Compare the image text labels against the SPICE nodes.

4.  If you find errors (especially missing labels like 'BAT' replaced by generic names), use the `FileEditorTool` to overwrite {spice_file.name} with the corrected content.

5.  If the SPICE is correct, reply "PASSED".
""".strip()

    # 4. Prepare Message Content
    content_payload = [TextContent(text=user_instruction)]
    
    # Attach Segmented Image (High Resolution Focus)
    content_payload.append(ImageContent(image_urls=[seg_img_url]))
    
    # Attach Full Schematic (Global Context) if available
    if full_schematic_url:
        content_payload.append(ImageContent(image_urls=[full_schematic_url]))

    # 5. Run Agent
    conversation = Conversation(
        agent=agent,
        workspace=cwd,
    )

    # Set System Persona
    conversation.send_message(
        Message(role="user", content=[TextContent(text=system_prompt)])
    )

    # Send Task
    conversation.send_message(
        Message(role="user", content=content_payload)
    )

    conversation.run()
    
    print(f"Finished review for {spice_file.name}")
    print("-" * 50)
    
    print(f"Total Review Cost: {llm.metrics.accumulated_cost}")

if __name__ == "__main__":
    # Example Usage
    run_spice_review_pipeline(
    segmented_images_subdir="../function_1/schematic_subcircuits",
    spice_input_subdir="spice_subcircuits",
    full_schematic_path="../function_1/original_full_schematic.png", # Path to the big image
    gcs_bucket_name="vhl"
    )